import { state } from "../state/store.js";
import { createCharacter, getCharacter, updateCharacter, deleteCharacter, duplicateCharacter } from "./character-manager.js";
import { characterTags, getContent, xpCost, definitionCost, CONTENT_TYPES } from "../data/content.js";

const DEF_TYPES = ["archetypes", "species", "backgrounds"];

export function renderCharacters(actions) {
  const container=document.getElementById("characters-section");
  container.innerHTML=`<div class="section-header"><div><div class="eyebrow">Campaign Library</div><h1>Characters</h1><p class="muted">Saved templates can be reused across encounters.</p></div><div class="toolbar"><button id="new-character" class="button-primary">+ New Character</button></div></div><div id="character-list" class="character-list"></div>`;
  container.querySelector("#new-character").onclick=()=>{const c=createCharacter({name:"New Character",type:"NPC",tier:1,extraXp:Number(state.settings.extraXpDefault||0),wounds:{current:0,max:10},shock:{current:0,max:10}});renderCharacterEditor(c.id,actions);};
  const list=container.querySelector("#character-list");
  if(!state.characters.length){list.innerHTML=`<div class="card empty-state">No character templates yet.</div>`;return;}
  state.characters.forEach(c=>{const spent=characterXP(c);const budget=Number(state.settings.xpBudgetsByTier?.[c.tier]||0)+Number(c.extraXp||0);const card=document.createElement("article");card.className="card character-card";card.innerHTML=`<div><div class="eyebrow">${esc(c.type)} · Tier ${c.tier}</div><h2>${esc(c.name)}</h2><div class="character-meta">${esc(c.faction||"No faction")} ${c.role?"· "+esc(c.role):""}</div><div class="character-meta" style="margin-top:7px">XP ${spent}/${budget} · Wounds ${c.wounds.max} · Shock ${c.shock.max} · DEF ${c.defense} · RES ${c.resilience}</div><div class="tag-cloud">${characterTags(c).map(t=>`<span class="tag-chip">${esc(t)}</span>`).join("")}</div></div><div class="character-actions"><button class="edit">Edit</button><button class="duplicate">Duplicate</button><button class="add button-primary">Add to Combat</button><button class="delete button-danger">Delete</button></div>`;card.querySelector(".edit").onclick=()=>renderCharacterEditor(c.id,actions);card.querySelector(".duplicate").onclick=()=>{duplicateCharacter(c.id);renderCharacters(actions);actions.toast("Character duplicated.");};card.querySelector(".add").onclick=()=>actions.addToCombat(c);card.querySelector(".delete").onclick=()=>{if(confirm(`Delete "${c.name}"?`)){deleteCharacter(c.id);renderCharacters(actions);actions.toast("Character deleted.");}};list.appendChild(card);});
}

export function renderCharacterEditor(id,actions){
  const c=getCharacter(id);if(!c)return;const container=document.getElementById("characters-section");
  const defs=state.definitions||{};
  container.innerHTML=`<div class="section-header"><div><div class="eyebrow">Character Template</div><h1>Edit Character</h1></div><button id="back">← Character Library</button></div>
  <div class="card editor-section"><h2>Identity & XP</h2><div class="grid grid-2">
    <div class="field"><label>Name</label><input id="name" value="${esc(c.name)}"></div><div class="field"><label>Type</label><select id="type">${["PC","NPC","Enemy","Ally"].map(x=>`<option ${c.type===x?"selected":""}>${x}</option>`).join("")}</select></div>
    <div class="field"><label>Tier</label><select id="tier">${[1,2,3,4,5].map(t=>`<option value="${t}" ${Number(c.tier)===t?"selected":""}>Tier ${t}</option>`).join("")}</select></div><div class="field"><label>Extra XP</label><input id="extra-xp" type="number" min="0" value="${Number(c.extraXp||0)}"></div>
    <div class="field"><label>Archetype</label><select id="archetype"><option value="">None</option>${(defs.archetypes||[]).map(x=>`<option value="${x.id}" ${c.archetype===x.id?"selected":""}>${esc(x.name)}</option>`).join("")}</select></div>
    <div class="field"><label>Species</label><select id="species"><option value="">None</option>${(defs.species||[]).map(x=>`<option value="${x.id}" ${c.species===x.id?"selected":""}>${esc(x.name)}</option>`).join("")}</select></div>
    <div class="field"><label>Background</label><select id="background"><option value="">None</option>${(defs.backgrounds||[]).map(x=>`<option value="${x.id}" ${c.background===x.id?"selected":""}>${esc(x.name)}</option>`).join("")}</select></div>
    <div class="field"><label>Custom tags</label><input id="tags" value="${esc((c.tags||[]).join(", "))}" placeholder="Veteran, Inquisitorial, Psyker"></div>
  </div><div id="xp-preview" class="xp-summary"></div></div>
  <div class="card editor-section"><h2>Combat Profile</h2><div class="grid grid-2"><div class="field"><label>Faction</label><input id="faction" value="${esc(c.faction)}"></div><div class="field"><label>Role</label><input id="role" value="${esc(c.role)}"></div><div class="field"><label>Maximum Wounds</label><input id="wounds" type="number" min="0" value="${c.wounds.max}"></div><div class="field"><label>Maximum Shock</label><input id="shock" type="number" min="0" value="${c.shock.max}"></div><div class="field"><label>Defense</label><input id="defense" type="number" value="${c.defense}"></div><div class="field"><label>Resilience</label><input id="resilience" type="number" value="${c.resilience}"></div><div class="field"><label>Default Initiative</label><input id="initiative" type="number" value="${c.initiative}"></div><div class="field"><label>Portrait path / URL</label><input id="portrait" value="${esc(c.portrait)}"></div></div></div>
  <div class="card editor-section"><h2>Notes</h2><textarea id="notes" rows="8" placeholder="Background, tactics, reminders...">${esc(c.notes)}</textarea></div>
  <div class="card"><div class="toolbar"><button id="open-builder" class="button-primary">Open Character Builder</button><button id="save">Save Character</button><button id="save-combat">Save and Add to Combat</button><button id="back2">Cancel</button></div></div>`;

  const updateXP=()=>{const tier=Number(container.querySelector("#tier").value);const extra=Math.max(0,Number(container.querySelector("#extra-xp").value)||0);const budget=Number(state.settings.xpBudgetsByTier?.[tier]||0)+extra;const spent=characterXP({...c,tier,extraXp:extra});container.querySelector("#xp-preview").innerHTML=`<strong>Tier ${tier} budget: ${budget} XP</strong><span>Current selected content: ${spent} XP</span>${spent>budget?`<span class="danger-text">Over budget by ${spent-budget} XP</span>`:"<span class="success-text">Within budget</span>"}`;};
  ["tier","extra-xp"].forEach(id=>container.querySelector("#"+id).oninput=updateXP);updateXP();
  const collect=()=>({name:container.querySelector("#name").value.trim()||"Unnamed Character",type:container.querySelector("#type").value,tier:Number(container.querySelector("#tier").value),extraXp:Math.max(0,Number(container.querySelector("#extra-xp").value)||0),archetype:container.querySelector("#archetype").value,species:container.querySelector("#species").value,background:container.querySelector("#background").value,tags:csv(container.querySelector("#tags").value),faction:container.querySelector("#faction").value.trim(),role:container.querySelector("#role").value.trim(),wounds:{...c.wounds,max:Number(container.querySelector("#wounds").value)||0},shock:{...c.shock,max:Number(container.querySelector("#shock").value)||0},defense:Number(container.querySelector("#defense").value)||0,resilience:Number(container.querySelector("#resilience").value)||0,initiative:Number(container.querySelector("#initiative").value)||0,portrait:container.querySelector("#portrait").value.trim(),notes:container.querySelector("#notes").value});
  const save=()=>updateCharacter(c.id,collect());
  container.querySelector("#save").onclick=()=>{save();actions.toast("Character saved.");actions.showPage("characters");};container.querySelector("#save-combat").onclick=()=>{save();actions.addToCombat(getCharacter(c.id));};container.querySelector("#back").onclick=()=>actions.showPage("characters");container.querySelector("#back2").onclick=()=>actions.showPage("characters");container.querySelector("#open-builder").onclick=()=>{save();state.builder.selectedCharacterId=c.id;CONTENT_TYPES.forEach(t=>state.builder.selections[t.key]=[...(getCharacter(c.id)[t.key]||[])]);actions.showPage("builder");};
}
function characterXP(c){let total=CONTENT_TYPES.reduce((sum,t)=>(c[t.key]||[]).reduce((s,id)=>{const item=getContent(t.key).find(x=>x.id===id);return s+(item?xpCost(item,c.tier||1)+Number(item.extraXp||0):0);},sum),0);["archetypes","species","backgrounds"].forEach(group=>{const id=c[group.slice(0,-1)];const def=(state.definitions?.[group]||[]).find(x=>x.id===id);total+=definitionCost(def,c.tier||1);});return total;}
function csv(v){return [...new Set(v.split(",").map(x=>x.trim()).filter(Boolean))];}
function esc(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
